// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2k0XK_VU42ACS4hoXR9KUNrLA5_R0BP8',
    appId: '1:43278493204:web:239d17a5712a3cc3182901',
    messagingSenderId: '43278493204',
    projectId: 'hirehubpro-52262',
    authDomain: 'hirehubpro-52262.firebaseapp.com',
    storageBucket: 'hirehubpro-52262.firebasestorage.app',
    measurementId: 'G-SSK6MDW3DE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbJgpSdPDOM0PjyawarE3dMtHnnHW-J6k',
    appId: '1:43278493204:android:831d4a08eacfeed2182901',
    messagingSenderId: '43278493204',
    projectId: 'hirehubpro-52262',
    storageBucket: 'hirehubpro-52262.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMbepS4jKsnPX8SHe4do1A9yTFUKkhNPk',
    appId: '1:43278493204:ios:ae32dfada2cefc30182901',
    messagingSenderId: '43278493204',
    projectId: 'hirehubpro-52262',
    storageBucket: 'hirehubpro-52262.firebasestorage.app',
    iosBundleId: 'com.example.hirehubUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMbepS4jKsnPX8SHe4do1A9yTFUKkhNPk',
    appId: '1:43278493204:ios:ae32dfada2cefc30182901',
    messagingSenderId: '43278493204',
    projectId: 'hirehubpro-52262',
    storageBucket: 'hirehubpro-52262.firebasestorage.app',
    iosBundleId: 'com.example.hirehubUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2k0XK_VU42ACS4hoXR9KUNrLA5_R0BP8',
    appId: '1:43278493204:web:b7706d1515366bee182901',
    messagingSenderId: '43278493204',
    projectId: 'hirehubpro-52262',
    authDomain: 'hirehubpro-52262.firebaseapp.com',
    storageBucket: 'hirehubpro-52262.firebasestorage.app',
    measurementId: 'G-DJ2KDKBW3W',
  );
}
