# Generated by Django 5.0.1 on 2025-10-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('owner', 'Owner')], max_length=10),
        ),
    ]
