# Generated by Django 5.0.1 on 2026-02-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_alter_customuser_user_type_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(default='recruiter', max_length=10),
        ),
    ]
