# Generated by Django 5.0.1 on 2026-02-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_alter_customuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default='+91 0000000000', max_length=20)),
                ('whatsapp_number', models.CharField(default='+91 0000000000', max_length=20)),
                ('email', models.EmailField(default='contact@hirehub.com', max_length=254)),
                ('address', models.TextField(blank=True)),
                ('whatsapp_link', models.URLField(blank=True, help_text='Direct link for WhatsApp chat')),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
