# Generated by Django 5.0.1 on 2026-03-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_platformsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='email',
            field=models.EmailField(default='contact@mezbanmanpower.com', max_length=254),
        ),
    ]
