# Generated by Django 5.0.1 on 2025-09-22 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('head_office_address', models.TextField()),
                ('contact_number', models.CharField(max_length=20)),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_contact', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='logos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('responsibilities', models.TextField()),
                ('qualifications', models.TextField()),
                ('working_time', models.CharField(max_length=100)),
                ('working_days', models.CharField(max_length=100)),
                ('salary', models.CharField(blank=True, max_length=100)),
                ('annual_leave', models.IntegerField(default=0)),
                ('benefits', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moderator.companyprofile')),
            ],
        ),
    ]
