# Generated by Django 5.0.1 on 2025-10-07 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0004_jobpost_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='title',
            new_name='position',
        ),
    ]
