# Generated by Django 5.0.1 on 2025-10-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0005_rename_title_jobpost_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='no_of_vacancies',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
