# Generated by Django 5.0.1 on 2026-02-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0009_jobpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='head_office_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='recruiter_contact',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='recruiter_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
