# Generated by Django 5.0.1 on 2026-02-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderator', '0010_alter_companyprofile_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='accommodation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='industry',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='meals',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
